# Base layer
FROM python:3.12-slim

# Meta
LABEL maintainer="m.astashonak@gmail.com"

# Disable cache files
ENV PYTHONDONTWRITEBYTECODE=1 
ENV PYTHONUNBUFFERED=1

# Working directory
WORKDIR /app
COPY ../app/frontend/ /app/frontend

# Install dependencies
RUN pip install streamlit

# Open port
EXPOSE 8501

# Start frontend
CMD ["streamlit", "run", "/app/frontend/app.py"]